# Generated by Django 2.2.24 on 2021-10-21 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='EnderecoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Endereço Aluno',
                'verbose_name_plural': 'Endereços Alunos',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_materia', models.CharField(max_length=20)),
                ('nome_professor', models.CharField(max_length=100)),
                ('trimestre', models.CharField(choices=[('1Tri', '1-Trimestre'), ('2Tri', '2-Trimestre'), ('3Tri', '3-Trimestre')], max_length=4)),
                ('trabalhos_nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prova_nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=9)),
                ('contato', models.CharField(choices=[('CEL', 'Celular'), ('TEL', 'Telefone')], max_length=3)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='alunos.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100, unique=True)),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_boletim', models.CharField(max_length=100)),
                ('nome_turma', models.CharField(max_length=50)),
                ('aprovado', models.BooleanField(default=True)),
                ('Matricula_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletim', to='alunos.MatriculaAluno')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco_aluno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.EnderecoAluno'),
        ),
    ]
