# Generated by Django 3.2.10 on 2022-02-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='boletim',
            new_name='Boletim_nota',
        ),
    ]
