# Generated by Django 3.2.10 on 2022-02-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='password',
            field=models.CharField(db_column='password', max_length=254),
        ),
    ]
