# Generated by Django 3.2.10 on 2022-02-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_rename_boletim_nota_nota_bpoletim_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='Bpoletim_nota',
            new_name='Boletim_nota',
        ),
    ]
